// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetDnsRecordsFilter {
    /**
     * Record subdomain.
     */
    subdomain?: string;
    /**
     * Record type. Valid types are: A, MX, CNAME, ALIAS, TXT, NS, AAAA, SRV, TLSA, CAA, HTTPS, SVCB.
     */
    type?: string;
}

export interface GetDnsRecordsFilterArgs {
    /**
     * Record subdomain.
     */
    subdomain?: pulumi.Input<string>;
    /**
     * Record type. Valid types are: A, MX, CNAME, ALIAS, TXT, NS, AAAA, SRV, TLSA, CAA, HTTPS, SVCB.
     */
    type?: pulumi.Input<string>;
}

