// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DomainNameservers extends pulumi.CustomResource {
    /**
     * Get an existing DomainNameservers resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DomainNameserversState, opts?: pulumi.CustomResourceOptions): DomainNameservers {
        return new DomainNameservers(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'porkbun:index/domainNameservers:DomainNameservers';

    /**
     * Returns true if the given object is an instance of DomainNameservers.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DomainNameservers {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DomainNameservers.__pulumiType;
    }

    declare public readonly domain: pulumi.Output<string>;
    declare public readonly nameservers: pulumi.Output<string[]>;

    /**
     * Create a DomainNameservers resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainNameserversArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DomainNameserversArgs | DomainNameserversState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DomainNameserversState | undefined;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["nameservers"] = state?.nameservers;
        } else {
            const args = argsOrState as DomainNameserversArgs | undefined;
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if (args?.nameservers === undefined && !opts.urn) {
                throw new Error("Missing required property 'nameservers'");
            }
            resourceInputs["domain"] = args?.domain;
            resourceInputs["nameservers"] = args?.nameservers;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DomainNameservers.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DomainNameservers resources.
 */
export interface DomainNameserversState {
    domain?: pulumi.Input<string>;
    nameservers?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a DomainNameservers resource.
 */
export interface DomainNameserversArgs {
    domain: pulumi.Input<string>;
    nameservers: pulumi.Input<pulumi.Input<string>[]>;
}
