// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDomains(opts?: pulumi.InvokeOptions): Promise<GetDomainsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("porkbun:index/getDomains:getDomains", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getDomains.
 */
export interface GetDomainsResult {
    readonly domains: outputs.GetDomainsDomain[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
export function getDomainsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDomainsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("porkbun:index/getDomains:getDomains", {
    }, opts, utilities.getPackage());
}
